export const FETCH_CURRENCY_RATES = "FETCH_CANDIDATES";
export const FETCH_CURRENCY_RATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CURRENCY_NAMES = "FETCH_CURRENCY_NAMES";
export const FETCH_CURRENCY_NAMES_SUCCESS = "FETCH_CURRENCY_NAMES_SUCCESS";
